# Gnuplot script to plot the data from generated by testing the model against Bart 1968

set terminal postscript color

set xlabel 'Viscosity Ratio'
set ylabel 'Dimensionless Velocity'

set logscale x

set xrange[0.001:1000]
set yrange[0.4:1]

set key below title 'Sphere Position'

set output 'viscos_rat.eps'

plot 'pos_sort.dat' u 2:(stringcolumn(1) eq '2'? $3:1/0) w lines title '2', \
     'pos_sort.dat' u 2:(stringcolumn(1) eq '3'? $3:1/0) w lines title '3', \
     'pos_sort.dat' u 2:(stringcolumn(1) eq '4'? $3:1/0) w lines title '4', \
     'pos_sort.dat' u 2:(stringcolumn(1) eq '5'? $3:1/0) w lines title '5', \
     'pos_sort.dat' u 2:(stringcolumn(1) eq '6'? $3:1/0) w lines title '6', \
     'pos_sort.dat' u 2:(stringcolumn(1) eq '7'? $3:1/0) w lines title '7', \
     'pos_sort.dat' u 2:(stringcolumn(1) eq '8'? $3:1/0) w lines title '8', \
     'pos_sort.dat' u 2:(stringcolumn(1) eq '9'? $3:1/0) w lines title '9', \
     'pos_sort.dat' u 2:(stringcolumn(1) eq '10'? $3:1/0) w lines title '10'


set xlabel 'Sphere Position'
set ylabel 'Dimensionless Velcoity'

unset logscale x

set xrange[2:10]

set key below title 'Viscosity Ratio'

set output 'pos.eps'

plot 'viscos_sort.dat' u 2:(stringcolumn(1) eq '0.001'? $3:1/0) w lines title '0.001', \
     'viscos_sort.dat' u 2:(stringcolumn(1) eq '0.01'? $3:1/0) w lines title '0.01', \
     'viscos_sort.dat' u 2:(stringcolumn(1) eq '0.1'? $3:1/0) w lines title '0.1', \
     'viscos_sort.dat' u 2:(stringcolumn(1) eq '1'? $3:1/0) w lines title '1', \
     'viscos_sort.dat' u 2:(stringcolumn(1) eq '10'? $3:1/0) w lines title '10', \
     'viscos_sort.dat' u 2:(stringcolumn(1) eq '100'? $3:1/0) w lines title '100', \
     'viscos_sort.dat' u 2:(stringcolumn(1) eq '1000'? $3:1/0) w lines title '1000'
